Support Humble
rt-net/rt_usb_9axisimu_driver pull request #42
Opened 2023-01-19 04:36 UTC by shu-rt

# What does this implement/fix?

Humbleで動作確認ができたので、READMEのリンクなどを更新

# Does this close any currently open issues?

No

# How has this been tested?

実機を用いて動作確認を行った

# Any other comments?

# Checklists

- [x]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [x]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2023-01-20 01:11 UTC, ShotaAk commented
KineticとDashingはサポートが切れたので削除をお願いします。
（ステータスバッジも見れないので）

また、Noeticには対応しているので、行の追加をお願いします。

![image](https://user-images.githubusercontent.com/18494952/213596505-2b7d1caf-6926-4efa-bf80-93665a2847a4.png)

![image](https://user-images.githubusercontent.com/18494952/213596706-3a7e0df4-b6e2-4eed-bfe2-6546a1edf378.png)

2023-01-20 01:15 UTC, ShotaAk requested changes
コメントの確認お願いします。

また、PRのdescriptionに、動作テストに使用した環境（dockerイメージなど）と、動作テストに使用したコマンド、何を確認したのか、追記をお願いします。

2023-01-20 01:15 UTC, ShotaAk commented on README.md
>  $ sudo apt install ros-dashing-rt-usb-9axisimu-driver
dashingはサポートが切れたので削除お願いします。

2023-01-23 05:32 UTC, shu-rt commented on README.md
>  $ sudo apt install ros-dashing-rt-usb-9axisimu-driver
対応しました

2023-01-25 01:09 UTC, ShotaAk commented
Noetic対応の文言も追加お願いします。

![image](https://user-images.githubusercontent.com/18494952/214457252-dad13bf4-5141-4675-b085-107c9becccf1.png)

2023-01-25 02:11 UTC, ShotaAk commented
LGTM

2023-01-25 02:11 UTC, merged