Update checkDataFormat() to enable ASCII format check
rt-net/rt_usb_9axisimu_driver pull request #54
Opened 2024-04-10 05:06 UTC by YusukeKato

# What does this implement/fix?

# Does this close any currently open issues?

# How has this been tested?

# Any other comments?

# Checklists

- [ ]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [ ]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2024-04-17 05:48 UTC, YusukeKato commented
checkDataFormat()のwhile文でsleep(10ms)を実行していましたが、sleepがなくても正常に動作することが確認できたので削除しました。

それに伴って、概要欄に記載していた下記の文章も削除しました。
> 実機のIMUからデータを取得する際、while文が高速にループしているとread()に失敗するため、sleep処理（10ms）を追加しました。

2024-04-17 10:07 UTC, ShotaAk requested changes
実装内容はほとんど良いと思います。

書き方についてコメントしました。確認お願いします。

2024-04-17 10:07 UTC, ShotaAk commented on test/test_driver.cpp
> +    dummy_bin_imu_data[consts.IMU_BIN_HEADER_ID1] = 0x41;
同じ表記が2個あるので、関数を用意してまとめてほしいです。

例えばis_invalidみたいな引数を用意して、該当箇所だけデータを書き換えればスッキリすると思います。

ASCIIも同様に対応お願いします。

2024-04-17 10:07 UTC, ShotaAk commented on src/rt_usb_9axisimu_driver_component.cpp
> +    RCLCPP_INFO(this->get_logger(), "Data format is neither binary nor ascii.");
ここはINFOではなくWARNにしてください

2024-04-17 10:07 UTC, ShotaAk commented on src/rt_usb_9axisimu_driver.cpp
> +    // time out (default 5.0s)
ここのコメントは削除してください。

コメントでデフォルト値を書くと、実際のデフォルト値を変更した際にコメントの修正も必要になります。

2024-04-17 10:07 UTC, ShotaAk commented on src/rt_usb_9axisimu_driver.cpp
> +    // Measures for data formats that are neither Binary nor ASCII
ここのコメントも削除でOKです。
binary or asciiではない場合タイムアウトするのはコードを読んで分かるので。

2024-04-17 10:07 UTC, ShotaAk commented on src/rt_usb_9axisimu_driver.cpp
> +    double time_elapsed = (double)std::chrono::duration_cast<std::chrono::seconds>(end_time - start_time).count();
変数はできる限りconst autoにしてください。

2024-04-17 10:07 UTC, ShotaAk commented on src/rt_usb_9axisimu_driver.cpp
> +    int read_size = serial_port_->readFromDevice(read_buffer, sizeof(read_buffer));
const auto で宣言しましょう。

2024-08-02 05:18 UTC, YusukeKato commented
ここまでのレビューコメントに対応しました。

2024-08-05 09:40 UTC, YusukeKato commented
## 概要
ASCIIデータの読み込み時にASCII形式の判定に失敗する場合があったため、修正を行いました。
実機でもASCIIとBinaryのデータ、どちらでもデータが読み込めることを確認しました。

## 原因
BinaryとASCIIのデータが全て揃っている状態でないとデータ形式を判定できないが、従来の実装方法だとタイミングによってデータが欠ける可能性があったため。

## 修正内容
readFromDevice()でIMUからデータを取得する際、一度で1セット分のデータ全てを取得できないようだったので（下記参考）、取得したデータを貯められるように変更しました。
Binary形式の判定では貯めたデータ内の中から「0xff」を見つけて、そこを基準に判定します。
ASCII形式の判定では貯めたデータ内の改行文字から次の改行文字までの間のデータを見て判定します。

## ASCIIデータ出力時のreadFromDevice()のログ
readFromDevice()実行1回目↓
```
read_size: 30
25,0.003193,0.000000,0.000000,
```

readFromDevice()実行2回目↓
```
read_size: 29
0.011230,-0.752930,-0.669922,
```

readFromDevice()実行3回目↓
```
read_size: 46
-316.200012,-594.599976,-201.899994,40.849045
```

2024-08-06 02:11 UTC, ShotaAk requested changes
動作OKです。細かいところにコメントしました

2024-08-06 02:11 UTC, ShotaAk commented on include/rt_usb_9axisimu_driver/rt_usb_9axisimu_driver.hpp
> +  unsigned int ascii_read_buffer_idx = 0;
メンバ変数は末尾にアンダーバーを付けてください

2024-08-06 02:11 UTC, ShotaAk commented on include/rt_usb_9axisimu_driver/rt_usb_9axisimu_driver.hpp
> +  unsigned char bin_read_buffer[256];
256を定数化してください。

`constexpr int READ_BUFFER_SIZE = 256;`

2024-08-06 05:58 UTC, ShotaAk approved these changes
LGTMです

2024-08-06 05:58 UTC, merged