Add test for readSensorData()
rt-net/rt_usb_9axisimu_driver pull request #57
Opened 2024-08-07 00:53 UTC by YusukeKato

# What does this implement/fix?

# Does this close any currently open issues?

# How has this been tested?

# Any other comments?

# Checklists

- [ ]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [ ]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2024-08-19 02:43 UTC, ShotaAk requested changes
いくつかコメントしたので確認お願いします。

2024-08-19 02:43 UTC, ShotaAk commented on include/rt_usb_9axisimu_driver/rt_usb_9axisimu_driver.hpp
> +  }
テストのために追加された関数ですが、
ユーザ（またはコードのメンテナ）が間違って使用する可能性があるため、追加しないで欲しいです。

2024-08-19 02:43 UTC, ShotaAk commented on test/test_driver.cpp
> +  void set_data (short int test_val) {
set_data関数はコンストラクタのみで使用されるため、privateにしてください。

ReadAsciiTestParamも同様です。

2024-08-19 02:43 UTC, ShotaAk commented on test/test_driver.cpp
> +  short int temp;
16ビットのデータだと分かるように、uint16_t型が使えるか試してほしいです。

https://cpprefjp.github.io/reference/cstdint/uint16_t.html

2024-08-19 02:43 UTC, ShotaAk commented on test/test_driver.cpp
> +}
関数をまとめずに、high_8bit、low_8bitのような２つの関数を用意したほうが読みやすいです。

2024-08-19 02:43 UTC, ShotaAk commented on test/test_driver.cpp
> +  short int temp;
他の箇所で、short intを使っている場合も、同様に対応お願いします。

2024-08-19 02:43 UTC, ShotaAk commented on test/test_driver.cpp
> +  driver.setBinaryFormat();
別のコメントにも記載しましたが、setBinaryFormat関数を使わずにテストを記述してください。

2024-08-19 02:43 UTC, ShotaAk commented on test/test_driver.cpp
> +                                         double *gyro, double *acc, double *mag, double temp) {
既存のテストコードに影響が出ないように、変数を減らした関数も用意してください。

```cpp
unsigned int create_dummy_ascii_imu_data(unsigned char *buf, bool is_invalid) {
  // いろいろ初期化した後に、
  return create_dummy_ascii_imu_data(buf, is_invalid, gyro, acc, mag, temp);
}
```

2024-08-19 02:43 UTC, ShotaAk commented on test/test_driver.cpp
> +  auto data = ReadBinaryTestParam(0);
既存のテストコードを変更しなくて良いように、`create_dummy_ascii_imu_data`のところでコメントしています。

2024-08-19 02:43 UTC, ShotaAk commented on test/test_driver.cpp
> +      ans_temp = (double)(test_val / consts.CONVERTOR_RAW2C_1 + consts.CONVERTOR_RAW2C_2);
ここについて、数値計算の正しさを検証したいため、
直接数値を使ってもらえませんか？

この実装の場合、定数クラスの値が間違っていてもテストが通ってしまいます。
※定数クラスを使うことで、メンテンナンス性が上がるというメリットはありますが。

例：

```cpp
ans_gyro[0] = ans_gyro[1] = ans_gyro[2] = (double)(test_val / 16.4 * M_PI / 180.0);
```

2024-08-19 05:39 UTC, YusukeKato commented on test/test_driver.cpp
> +  short int temp;
uint16_t型だと符号無しなのでint16_t型に変更しました。

2024-08-19 08:24 UTC, YusukeKato commented
全てのコメントに対応しました。

2024-08-20 01:16 UTC, ShotaAk requested changes

2024-08-20 01:16 UTC, ShotaAk commented on test/test_driver.cpp
> +    consts.ChangeConvertor(test_firmfare_ver);
細かい指摘です。constsはクラス内で使用されていないので削除してください。

Asciiの方も同様に削除してください。

2024-08-20 01:57 UTC, ShotaAk approved these changes
LGTM

2024-08-20 01:57 UTC, merged